### ISSUE TITLE
Fix Vulnerabilities in Docker Image

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/container-kibana#2]
**Note:** Please file issues for subcomponents under the appropriate repo

| Component       | Repo                                                                                       |
| --------------- | ------------------------------------------------------------------------------------------ |
| solas           | [samsung-cnct/solas](https://github.com/samsung-cnct/solas/issues/new)                     |
| solas-container | [samsung-cnct/solas-container](https://github.com/samsung-cnct/solas-container/issues/new) |
| solas-chart     | [samsung-cnct/solas-chart](https://github.com/samsung-cnct/solas-chart/issues/new)         |

**What keywords did you search in solas issues before filing this one?** (If you have found any duplicates, you should reply there instead.):
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Security risk

**Environment**:

Please be sure not to submit any confidential information (e.g. ssh keys, provider secrets, etc.) as issues are publicly accessible.

**What happened**:
To see a list of known vulnerabilities check the quay image repo for kibana.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by coffeepac** [comment]
p1, bug

**Comment by coffeepac** [comment]
dupe of samsung-cnct/issues#68
