### ISSUE TITLE
port container-kibana to gitlab

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/container-kibana#7]
- [x]  Follow [instructions](https://github.com/samsung-cnct/solas/blob/master/docs/gitlab.md) to create  and edit`.gitlab-ci.yaml` at project root from [template](https://github.com/samsung-cnct/solas-container/blob/master/.gitlab-ci.yml), as well as create gitlab secret variable. 
- [x] Remove the `Jenkinsfile` in the current repo 
- [x] When PR has merged, make sure that new kibana image is being created on quay. Afterwards,  please head back to the [umbrella ticket](https://github.com/samsung-cnct/issues/issues/89) and check off the `container-kibana`

**Comment by DStorck** [comment]
This is a test ticket so I can trial run the process.

**Comment by DStorck** [comment]
https://github.com/samsung-cnct/container-kibana/pull/12

**Comment by guineveresaenger** [comment]
Looks good!
